# Generated by Django 6.0.6 on 2026-06-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_space_length_space_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='space',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
