# Generated by Django 4.2.30 on 2026-06-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_version_space_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='circulation_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(default='Unknown Client', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='max_buildable_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('concept', 'Concept'), ('in_design', 'In Design'), ('review', 'Review'), ('completed', 'Completed')], default='concept', max_length=20),
        ),
        migrations.AddField(
            model_name='space',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('living', 'Living'), ('office', 'Office'), ('circulation', 'Circulation'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(default='other', unique=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='space',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
