# Generated by Django 6.0.6 on 2026-06-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='space',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
